name: ci
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  syntax-elvish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Enforce valid syntax
        uses: chlorm/ci-elvish-syntax@master
